# Built in Mathematical Functions in NumPy
Here are some common NumPy methods that are frequently used for statistical and mathematical operations:

### np.mean() – Compute the mean (average) of an array.

np.mean(arr)

### np.std() – Compute the standard deviation of an array.

np.std(arr)

### np.var() – Compute the variance of an array.

np.var(arr)

### np.min() – Compute the minimum value of an array.

np.min(arr)

### np.max() – Compute the maximum value of an array.

np.max(arr)

### np.sum() – Compute the sum of all elements in an array.

np.sum(arr)

### np.prod() – Compute the product of all elements in an array.

np.prod(arr)

### np.median() – Compute the median of an array.

np.median(arr)

### np.percentile() – Compute the percentile of an array.

np.percentile(arr, 50)  # For the 50th percentile (median)

### np.argmin() – Return the index of the minimum value in an array.

np.argmin(arr)

### np.argmax() – Return the index of the maximum value in an array.

np.argmax(arr)

### np.corrcoef() – Compute the correlation coefficient matrix of two arrays.

np.corrcoef(arr1, arr2)

### np.unique() – Find the unique elements of an array.

np.unique(arr)

### np.diff() – Compute the n-th differences of an array.

np.diff(arr)

### np.cumsum() – Compute the cumulative sum of an array.

np.cumsum(arr)

### np.linspace() – Create an array with evenly spaced numbers over a specified interval.

np.linspace(0, 10, 5)  # 5 numbers from 0 to 10

### np.log() – Compute the natural logarithm of an array.

np.log(arr)

### np.exp() – Compute the exponential of an array.

np.exp(arr)

In [1]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])

In [2]:
np.mean(arr)

np.float64(3.0)

In [3]:
np.std(arr)

np.float64(1.4142135623730951)

In [4]:
np.var(arr)

np.float64(2.0)

In [5]:
np.min(arr)

np.int64(1)

In [6]:
np.max(arr)

np.int64(5)

In [7]:
np.sum(arr)

np.int64(15)

In [8]:
np.prod(arr)

np.int64(120)

In [9]:
np.median(arr)

np.float64(3.0)

In [10]:
np.percentile(arr, 50) 

np.float64(3.0)

In [11]:
np.argmin(arr)

np.int64(0)

In [12]:
np.argmax(arr)

np.int64(4)

In [14]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([10, 20, 30])

In [15]:
np.corrcoef(arr1, arr2)

array([[1., 1.],
       [1., 1.]])

In [16]:
np.unique(arr)

array([1, 2, 3, 4, 5])

In [17]:
np.diff(arr)

array([1, 1, 1, 1])

In [18]:
np.cumsum(arr)

array([ 1,  3,  6, 10, 15])

In [19]:
np.linspace(0, 10, 5) 

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [20]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [21]:
np.exp(arr)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])