# 1. Creating NumPy Arrays

In [5]:
import numpy as np
arr1 = np.array([1,2,3,4,5]) #1D array
arr2 = np.array([[1,2,3],[4,5,6]]) #2D array
print("1D array is :",(arr1))
print("2D array is :",(arr2))

1D array is : [1 2 3 4 5]
2D array is : [[1 2 3]
 [4 5 6]]


In [28]:
np.zeros((3, 3))    # 3x3 array of zeros
print(np.zeros((3, 3)))

np.ones((2, 4))     # 2x4 array of ones
print(np.ones((2, 4)))

np.full((2, 2), 7)  # 2x2 array filled with 7
print(np.full((2, 2), 7) )

np.eye(4)           # 4x4 identity matrix
print(np.eye(4))

np.arange(1, 10, 2) # [1, 3, 5, 7, 9] (like range)
print(np.arange(1, 10, 2))

np.linspace(0, 1, 5) # [0. 0.25 0.5 0.75 1.] (evenly spaced)
print(np.linspace(0, 1, 5))


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[7 7]
 [7 7]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[1 3 5 7 9]
[0.   0.25 0.5  0.75 1.  ]


# Checking Array Properties

In [11]:
arr = np.array([[10, 20, 30], [40, 50, 60]])

print("Shape:", arr.shape)   # (2, 3) → 2 rows, 3 columns
print("Size:", arr.size)     # 6 → total elements
print("Dimensions:", arr.ndim) # 2 → 2D array
print("Data type:", arr.dtype) # int64 (or int32 on Windows)

Shape: (2, 3)
Size: 6
Dimensions: 2
Data type: int64


# Changing Data Types


In [13]:
arr = np.array([1, 2, 3], dtype=np.float32)  # Explicit type
print(arr.dtype)  # float32

arr_int = arr.astype(np.int32)  # Convert float to int
print(arr_int)  # [1 2 3]

float32
[1 2 3]


 # Reshaping and Flattening Arrays

In [14]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)  # (2, 3)

reshaped = arr.reshape((3, 2))  # Change shape
print(reshaped)
# [[1 2]
#  [3 4]
#  [5 6]]

flattened = arr.flatten()  # Convert 2D → 1D
print(flattened)  # [1 2 3 4 5 6]

(2, 3)
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


 # NumPy Practice – Matrix Operations

In [25]:
import numpy as np

# Step 1: Create a 3x3 matrix using arange and reshape
arr = np.arange(1, 10).reshape(3, 3)

print("Original Matrix:")
print(arr)

# Step 2: Find overall mean of matrix
overall_mean = arr.mean()
print("\nOverall Mean:", overall_mean)

# Step 3: Find column-wise sum (axis=0 → vertical)
column_sum = arr.sum(axis=0)
print("\nColumn-wise Sum:", column_sum)

# Step 4: Find row-wise sum (axis=1 → horizontal)
row_sum = arr.sum(axis=1)
print("\nRow-wise Sum:", row_sum)

# Step 5: Find column-wise mean
column_mean = arr.mean(axis=0)
print("\nColumn-wise Mean:", column_mean)

# Step 6: Find row-wise mean
row_mean = arr.mean(axis=1)
print("\nRow-wise Mean:", row_mean)

Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Overall Mean: 5.0

Column-wise Sum: [12 15 18]

Row-wise Sum: [ 6 15 24]

Column-wise Mean: [4. 5. 6.]

Row-wise Mean: [2. 5. 8.]
