# Exercises for Practice


### Create a 3×3 array filled with random numbers and print its shape.

In [2]:
import numpy as np
arr = np.random.rand(3,3) # float random numbers
# np.random.randint(1, 100, (3, 3)) (integer random numbers)
print(arr)
print("Shape :",arr.shape)

[[0.09312511 0.20893352 0.41011413]
 [0.61779846 0.69161511 0.84033545]
 [0.4102119  0.87786657 0.65088641]]
Shape : (3, 3)


### Convert an array of floats [1.1, 2.2, 3.3] into integers.

In [4]:
arr = np.array([1.1,2.2,3.3])
arr_int = arr.astype(int)
print(arr_int)
print(arr_int.dtype)

[1 2 3]
int64


### Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6].

In [5]:
arr = np.array([1,2,3,4,5,6])
even = (arr[arr % 2 == 0])
print(even)

[2 4 6]


In [6]:
#arr = np.array([1,2,3,4,5,6])
#idx = [1,3,5]
#print(arr[idx])

### Reshape 1D array of size 9 into 3×3 matrix.

In [10]:
arr = np.arange(1,10)
print("1D array :",arr)
a1 = arr.reshape(3,3)
print(a1)
print("shape of the array is :",a1.shape)

1D array : [1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
shape of the array is : (3, 3)


### Use boolean masking to filter numbers greater than 50 in an array.

In [12]:
arr = np.array([10, 60, 45, 80, 30, 90])
a2 = arr > 50
print("the greater number of 50 is :",arr[a2])  # print(arr[arr > 50])

the greater number of 50 is : [60 80 90]
