### Q1 Array Creation

Create an array from 1 to 15 and reshape it into 3×5 matrix.

In [2]:
import numpy as np 
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
print(arr)
reshape = arr.reshape(3,5)
print(reshape)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


### Q2 Basic Properties

Using the array from Q1:

Find:

shape

size

number of dimensions

data type

In [3]:
print(reshape.shape)

(3, 5)


In [4]:
print(reshape.size)

15


In [5]:
print(reshape.ndim)

2


In [6]:
print(reshape.dtype)

int64


### Q3 Indexing

From the same matrix:

1️⃣ Print the element at row 2 column 3

2️⃣ Print the last row

3️⃣ Print the second column

In [7]:
print(reshape[1,2])

8


In [8]:

print(reshape[2:])

[[11 12 13 14 15]]


In [9]:
print(reshape[:,1])

[ 2  7 12]


### Q4 Slicing

Extract the middle 2×3 submatrix.

In [10]:
print(reshape[1:,1:4])

[[ 7  8  9]
 [12 13 14]]


### Q5 Mathematical Functions

Given:

arr1 = np.array([10,20,30,40,50])

Find:

mean

standard deviation

variance

sum

cumulative sum

In [31]:
arr1 = np.array([10,20,30,40,50])
np.mean(arr1)


np.float64(30.0)

In [32]:
np.std(arr1)

np.float64(14.142135623730951)

In [33]:
np.var(arr1)

np.float64(200.0)

In [34]:
np.sum(arr1)

np.int64(150)

In [35]:
np.cumsum(arr1)

array([ 10,  30,  60, 100, 150])

### Q6 Logical Operations
arr2 = np.array([5,10,15,20,25,30])

Find numbers:

greater than 15

between 10 and 25

In [11]:
arr2 = np.array([5,10,15,20,25,30])
print(arr2[arr2 > 15])

[20 25 30]


In [12]:
print(arr2[(arr2 > 10) & (arr2 < 25)])

[15 20]


### Q7 np.where()

Using:

arr3 = np.array([12,18,25,30,45])

Replace:

numbers greater than 20 → 999

In [16]:
arr3 = np.array([12,18,25,30,45])
result = np.where(arr3 > 20, 999, arr3)
print(result)

[ 12  18 999 999 999]


### Q8 Broadcasting
a = np.array([[1],[2],[3]])
b = np.array([10,20,30])

Add both arrays using broadcasting.

In [52]:
a = np.array([[1],[2],[3]])
b = np.array([10,20,30])

print(a + b)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


### Q9 Sorting
arr4 = np.array([45,10,35,20,50])

Find:

sorted array

indices of sorted array

index of maximum value

In [53]:
arr4 = np.array([45,10,35,20,50])
np.sort(arr4)

array([10, 20, 35, 45, 50])

In [54]:
np.argsort(arr4)

array([1, 3, 2, 0, 4])

In [55]:
np.argmax(arr4)

np.int64(4)

### Q10 Stacking
c = np.array([1,2,3])
d = np.array([4,5,6])

Perform:

vertical stacking

horizontal stacking

In [56]:
c = np.array([1,2,3]) 
d = np.array([4,5,6])
np.vstack((c,d))

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
np.hstack((c,d))

array([1, 2, 3, 4, 5, 6])

### Q11 Splitting
arr5 = np.array([10,20,30,40,50,60])

Split into 3 equal parts.

In [59]:
arr5 = np.array([10,20,30,40,50,60])
np.split(arr5,3)

[array([10, 20]), array([30, 40]), array([50, 60])]

### Q12 Unique Values
arr6 = np.array([1,2,2,3,4,4,5,5])

Find unique values.

In [60]:
arr6 = np.array([1,2,2,3,4,4,5,5])
np.unique(arr6)

array([1, 2, 3, 4, 5])